server.port: 8085
spring.kafka.bootstrap-servers: BOOTSRAP-URLS
sasl:
  jaas:
    config: org.apache.kafka.common.security.plain.PlainLoginModule required username="USER-NAME" password="USER-PASSWORD";
  mechanism: PLAIN
perpetual: false
delete.enable: true
kafkaenv:
  topics:
    -
     name: testing
     numPartitions: 5
     replicationFactor: 3
     configs:
        cleanup.policy: delete
        delete.retention.ms: 86400000
        max.message.bytes: 2097165
        retention.bytes: -1
        retention.ms: 604800000
  acls:
    -
     principal: "User:7453"
     permission: ALLOW
     operation: WRITE
     resourceType: TOPIC
     resourceName: testing-123
     patternType: LITERAL

