server.port: 8085
spring.kafka.bootstrap-servers: BOOTSRAP-URLS
security:
  protocol: SASL_SSL
sasl:
  jaas:
    config: org.apache.kafka.common.security.plain.PlainLoginModule required username="USER-NAME" password="USER-PASSWORD";
  mechanism: PLAIN
ssl:
  truststore:
    location:
    password:
  keystore:
    location:
    password:
  key:
    password:
perpetual: false
delete.enable: true
base.prefix: com.confluent.
kafkaenv:
  topics:
    -
     name: test
     numPartitions: 10
     replicationFactor: 3
     configs:
        cleanup.policy: delete
        delete.retention.ms: 86400000
        max.message.bytes: 2097165
        retention.bytes: -1
        retention.ms: 604800000
    -
     name: com.confluent.test123
     numPartitions: 1
     replicationFactor: 3
     configs:
          cleanup.policy: delete
          delete.retention.ms: 86400000
          max.message.bytes: 2097165
          retention.bytes: -1
          retention.ms: 604800000
  acls:
    -
     principal: "User:7453"
     permission: ALLOW
     operation: WRITE
     resourceType: TOPIC
     resourceName: testing
     patternType: LITERAL

