server.port: 8085
spring.kafka.bootstrap-servers: BOOTSRAP-URLS
sasl:
  jaas:
    config: org.apache.kafka.common.security.plain.PlainLoginModule required username="USER-NAME" password="USER-PASSWORD";
  mechanism: PLAIN
perpetual: true
kafkaenv:
  topics:
    -
     name: test
     numPartitions: 3
     replicationFactor: 3
     configs:
        cleanup.policy: delete
        delete.retention.ms: 86400000
        max.message.bytes: 2097164
        retention.bytes: -1
        retention.ms: 604800000
  acls:
    -
     principal: "User:7453"
     permission: ALLOW
     operation: WRITE
     resourceType: TOPIC
     resourceName: rahul-topic
     patternType: LITERAL

